//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AestheticsMonitoringApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int QuestionId { get; set; }
        public QuestionType Type { get; set; }
        public string Wording { get; set; }
        public string Response { get; set; }
        public int SurveyId { get; set; }
    
        public virtual Survey Survey { get; set; }
    }
}
