//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiverKeeperDAL
{
    using System;
    
    public enum ResponseFormat : short
    {
        Alphanumeric = 1,
        Date = 2,
        SingleSelection = 3,
        MultipleSelection = 4
    }
}
